[tools]
coursier = "latest"
# java = "temurin-11.0.28+6"
java = "temurin-21"
lazygit = "latest"
lua = "5.1.1"
neovim = "latest"
node = "23.11.0"
opentofu = "1.10.5"
rust-analyzer = "latest"
scala = "2.13.18"
stylua = "latest"
terraform = "1.6.0"

[settings]
idiomatic_version_file_enable_tools = ["node"]
